/*
 * SeAT API
 * SeAT API Documentation. All endpoints require an API key.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.waw_eve.seat.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse20017
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-23T10:10:39.586058800+08:00[Asia/Shanghai]")
public class InlineResponse20017 {
	@SerializedName("data")
	private List<CharacterWalletJournal> data = null;

	@SerializedName("links")
	private ResourcePaginatedLinks links = null;

	@SerializedName("meta")
	private ResourcePaginatedMetadata meta = null;

	public InlineResponse20017 data(List<CharacterWalletJournal> data) {
		this.data = data;
		return this;
	}

	public InlineResponse20017 addDataItem(CharacterWalletJournal dataItem) {
		if (this.data == null) {
			this.data = new ArrayList<CharacterWalletJournal>();
		}
		this.data.add(dataItem);
		return this;
	}

	/**
	 * Get data
	 * 
	 * @return data
	 **/
	@Schema(description = "")
	public List<CharacterWalletJournal> getData() {
		return data;
	}

	public void setData(List<CharacterWalletJournal> data) {
		this.data = data;
	}

	public InlineResponse20017 links(ResourcePaginatedLinks links) {
		this.links = links;
		return this;
	}

	/**
	 * Get links
	 * 
	 * @return links
	 **/
	@Schema(description = "")
	public ResourcePaginatedLinks getLinks() {
		return links;
	}

	public void setLinks(ResourcePaginatedLinks links) {
		this.links = links;
	}

	public InlineResponse20017 meta(ResourcePaginatedMetadata meta) {
		this.meta = meta;
		return this;
	}

	/**
	 * Get meta
	 * 
	 * @return meta
	 **/
	@Schema(description = "")
	public ResourcePaginatedMetadata getMeta() {
		return meta;
	}

	public void setMeta(ResourcePaginatedMetadata meta) {
		this.meta = meta;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		InlineResponse20017 inlineResponse20017 = (InlineResponse20017) o;
		return Objects.equals(this.data, inlineResponse20017.data)
				&& Objects.equals(this.links, inlineResponse20017.links)
				&& Objects.equals(this.meta, inlineResponse20017.meta);
	}

	@Override
	public int hashCode() {
		return Objects.hash(data, links, meta);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class InlineResponse20017 {\n");

		sb.append("    data: ").append(toIndentedString(data)).append("\n");
		sb.append("    links: ").append(toIndentedString(links)).append("\n");
		sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
