/*
 * SeAT API
 * SeAT API Documentation. All endpoints require an API key.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.waw_eve.seat.client;

import com.waw_eve.seat.client.invoker.ApiException;
import com.waw_eve.seat.client.model.InlineResponse20017;
import com.waw_eve.seat.client.model.InlineResponse20026;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WalletApi
 */
@Ignore
public class WalletApiTest {

    private final WalletApi api = new WalletApi();

    /**
     * Get a paginated wallet journal for a character
     *
     * Returns a wallet journal
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void seatApiHttpControllersApiv2CharacterControllerGetWalletJournalTest() throws ApiException {
        Integer characterId = null;
        InlineResponse20017 response = api.seatApiHttpControllersApiv2CharacterControllerGetWalletJournal(characterId);

        // TODO: test validations
    }
    /**
     * Get a paginated wallet journal for a corporation
     *
     * Returns a wallet journal
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void seatApiHttpControllersApiv2CorporationControllerGetWalletJournalTest() throws ApiException {
        Integer corporationId = null;
        InlineResponse20026 response = api.seatApiHttpControllersApiv2CorporationControllerGetWalletJournal(corporationId);

        // TODO: test validations
    }
}
